# Generated by Django 3.1.7 on 2021-04-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shixun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=20)),
                ('movieActor', models.CharField(max_length=20)),
                ('movieTime', models.CharField(max_length=20)),
                ('movieGrade', models.CharField(max_length=20)),
            ],
        ),
    ]
