# Generated by Django 3.1.7 on 2021-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shixun', '0002_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodName', models.CharField(max_length=30)),
                ('goodLink', models.CharField(max_length=20)),
                ('goodPrice', models.CharField(max_length=20)),
                ('goodGrade', models.CharField(max_length=20)),
            ],
        ),
    ]
